android_build_config(
	name = 'build_config',
	package = 'com.github.piasy.okbuck.example.empty',
	visibility = [
		'PUBLIC',
	],
)

android_library(
	name = 'src',
	srcs = glob([
		'src/main/java/**/*.java',
	]),
	manifest = 'src/main/AndroidManifest.xml',
	annotation_processors = [
	],
	annotation_processor_deps = [
		'//.okbuck/annotation_processor_deps/libraries/emptylibrary:all_jars',
		'//.okbuck/annotation_processor_deps/libraries/emptylibrary:all_aars',
	],
	deps = [
		':build_config',
		'//.okbuck/common_deps/_anotherapp__app__dummylibrary__libraries_common__libraries_emptylibrary_:aar__support-v4-23.0.1.aar',
		'//.okbuck/common_deps/_anotherapp__app__dummylibrary__libraries_common__libraries_emptylibrary_:jar__support-annotations-23.0.1.jar',
		'//.okbuck/common_deps/_anotherapp__app__dummylibrary__libraries_common__libraries_emptylibrary_:aar__appcompat-v7-23.0.1.aar',
	],
	visibility = [
		'PUBLIC',
	],
)

project_config(
	src_target = '//libraries/emptylibrary:src',
	src_roots = [
		'src/main/java',
	],
)

